### ISSUE TITLE
[BUG] jq command not found error during nfs-provisioner

### ISSUE THREAD

**Issue by kjw3** [Qubinode/qubinode-installer#141] opened 2020-03-06 18:52 UTC
**Qubinode Version**  
Qubinode release v2.3.1  

**Describe the bug**
During OCP4 install, I see this after saying yes to configuring NFS provisioner

Now using project "default" on server "https://api.ocp42.kdjlab.com:6443".

Deployment started; you should monitor it with "oc get pods -n nfs-provisioner"

persistentvolumeclaim/image-registry-storage created
Error from server: Invalid JSON Patch
/home/qubinode/qubinode-installer/lib/qubinode_ocp4_utils.sh: line 454: jq: command not found

**To Reproduce**
1. Run the OCP4 installation
2. Answer yes when asked if I want to configure 
3. See above error about jq command not available

**Expected behavior**
jq should have been installed

**Hardware Profile infomation**  
sys-e200-8d (8c, 128GB, 1TB nvme)

**Comment by tosin2013** [comment] 2020-03-06 19:10
NFS provisioner role is still a wip we will add a fix for this.

**Comment by flyemsafe** [comment] 2020-03-22 23:14
Duplicate of #142

**Closed as completed** 2020-03-22 23:14 UTC
Labels: bug
