### ISSUE TITLE
DOC -- when using token you still need the kvm qcow image

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#359] opened 2021-03-26 19:29 UTC
If you are using tokens it should be:

* $HOME/qubinode-installer/ocp_token
* $HOME/qubinode-installer/rhsm_token
If you downloaded the files instead it should be:

* $HOME/qubinode-installer/pull-secret.txt
* $HOME/qubinode-installer/rhel-server-7.8-x86_64-kvm.qcow2
* $HOME/qubinode-installer/rhel-8.2-x86_64-kvm.qcow2

**Comment by flyemsafe** [comment] 2021-03-29 00:49
Comment duplicate of #360

**Closed as completed** 2021-06-09 22:16 UTC
Labels: wontfix, documentation
